// gen_l10n.swift — FCPX2AAF 本地化代码生成器（BuildToolPlugin 调用）。
//
// 由 Plugins/LocalizationGenerator 在每次 `swift build` / `swift test` 前自动调用，
// 读取 Localizable.xcstrings（Apple 字符串目录，Xcode 可可视化编辑），产出
// L10n.generated.swift（翻译文本内嵌，编译期校验键是否存在）。
//
// 设计要点（与项目纪律一致）：
// - 纯 Swift（仅依赖 Foundation），单一调用源 = BuildToolPlugin，开发/打包行为一致。
// - 翻译文本「内嵌」进生成的 Swift 枚举（非运行时查 bundle），无需 Bundle.module / .lproj。
//
// 入口用 @main 包裹（而非裸顶层语句）：这样无论 SwiftPM 以可执行模式还是 Xcode 预览以
// 库模式（-parse-as-library）编译都能通过，且全部状态收敛到 main() 局部，无全局可变状态。
//
// 手动调试用法（一般无需，plugin 已自动生成）：
//     cd tools/gen_l10n_tool && swift run gen_l10n_tool <Localizable.xcstrings> <output.swift>

import Foundation

@main
struct GenL10nTool {
    static func main() throws {
        func fail(_ msg: String) -> Never {
            FileHandle.standardError.write(Data(msg.utf8))
            exit(1)
        }

        let args = Array(CommandLine.arguments.dropFirst())
        guard args.count >= 2 else {
            fail("用法: gen_l10n <Localizable.xcstrings> <output.swift>\n")
        }
        let xcstrings = URL(fileURLWithPath: args[0])
        let output = URL(fileURLWithPath: args[1])

        guard let data = try? Data(contentsOf: xcstrings) else {
            fail("[gen_l10n] 未找到源文件: \(xcstrings.path)\n")
        }
        guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            fail("[gen_l10n] 无法解析 JSON: \(xcstrings.lastPathComponent)\n")
        }

        let sourceLang = (json["sourceLanguage"] as? String) ?? "zh-Hans"
        let strings = (json["strings"] as? [String: Any]) ?? [:]

        func isValidSwiftId(_ name: String) -> Bool {
            guard let first = name.first else { return false }
            if !(first.isLetter || first == "_") { return false }
            return name.allSatisfy { $0.isLetter || $0.isNumber || $0 == "_" }
        }

        func swiftStrLiteral(_ s: String) -> String {
            let escaped = s.replacingOccurrences(of: "\\", with: "\\\\")
                .replacingOccurrences(of: "\"", with: "\\\"")
                .replacingOccurrences(of: "\n", with: "\\n")
            return "\"\(escaped)\""
        }

        var keys: [String] = []
        var tableEntries: [String] = []

        for (key, value) in strings {
            guard isValidSwiftId(key) else {
                FileHandle.standardError.write(Data("[gen_l10n] 跳过非法键名（非 Swift 标识符）: \(key)\n".utf8))
                continue
            }
            guard let payload = value as? [String: Any],
                let locs = payload["localizations"] as? [String: Any]
            else {
                FileHandle.standardError.write(Data("[gen_l10n] 跳过缺少 localizations 的键: \(key)\n".utf8))
                continue
            }
            var perLang: [String: String] = [:]
            for (lang, info) in locs {
                if let infoDict = info as? [String: Any],
                    let unit = infoDict["stringUnit"] as? [String: Any],
                    let v = unit["value"] as? String
                {
                    perLang[lang] = v
                }
            }
            guard !perLang.isEmpty else {
                FileHandle.standardError.write(Data("[gen_l10n] 跳过无翻译的键: \(key)\n".utf8))
                continue
            }
            keys.append(key)
            let langItems = perLang.map { "\(swiftStrLiteral($0.key)): \(swiftStrLiteral($0.value))" }
                .joined(separator: ", ")
            tableEntries.append("        .\(key): [\(langItems)]")
        }

        guard !keys.isEmpty else {
            fail("[gen_l10n] 没有任何有效键，中止。\n")
        }

        let keysSorted = keys.sorted()
        let caseLines = keysSorted.map { "    case \($0)" }.joined(separator: "\n")
        let tableBlock = tableEntries.joined(separator: ",\n")

        let swift = """
            // AUTO-GENERATED by gen_l10n_tool — 禁止手改。
            // 修改文案请编辑 Localizable.xcstrings 后重跑构建（BuildToolPlugin 自动重新生成）。
            // 翻译文本内嵌于本文件，SwiftPM `swift build` 与 Xcode 构建行为一致（无需 Bundle.module）。
            import Foundation

            /// 本地化访问入口。键名即 Localizable.xcstrings 中的 key。
            enum L10n {
                /// 所有本地化键值（类型安全，编译期校验键是否存在）。
                enum Key: String, CaseIterable {
            \(caseLines)
                }

                /// 翻译表：键 → (语言代码 → 文本)。源语言为 \(swiftStrLiteral(sourceLang))。
                private static let table: [Key: [String: String]] = [
            \(tableBlock)
                ]

                /// **语言覆盖**（任务局部作用域）。`nil` = 跟随 `Locale.current`（生产行为）。
                ///
                /// **为什么需要**：设计稿的排版数字（面板 480×800、引导窗 503.3、按钮 50/102、
                /// 路径小标 226 …）全部按**中文**实测，「排版与设计稿一致」这类断言
                /// **只有钉在确定的中文下才有意义**。不钉就跟随 `Locale.current`，
                /// 于是同一份代码在英文机器上必红 —— 2026-09-17 CI 连续 6 次红即此因
                /// （19 个 issue 里 18 个都是它，而本地一直绿，只因为本机是中文环境）。
                ///
                /// **为什么用 `@TaskLocal` 而不是全局 `var`**：swift-testing 并行跑用例，
                /// 全局可变状态会串台（一个用例把语言改成英文，另一个正在渲染的用例跟着变）。
                /// 任务局部只在 `withValue` 闭包内生效、随子任务传播，天然按用例隔离。
                ///
                /// ⚠️ **生产代码从不设置它**：应用里 `tr` 永远走 `Locale.current`。
                @TaskLocal static var forcedLocale: Locale?

                /// 取本地化文本。解析顺序：精确语言匹配 → 同语族回退（如 zh-Hans/zh-Hant 互通）
                /// → 回退源语言（\(sourceLang)）。
                static func tr(_ key: Key, locale: Locale = .current) -> String {
                    let entry = Self.table[key] ?? [:]
                    let resolved = Self.forcedLocale ?? locale
                    let id = resolved.identifier.split(separator: "_").first.map(String.init) ?? \(swiftStrLiteral(sourceLang))
                    if let v = entry[id] { return v }
                    if id.hasPrefix("zh") {
                        return entry["zh-Hans"] ?? entry["zh-Hant"] ?? key.rawValue
                    }
                    return entry[\(swiftStrLiteral(sourceLang))] ?? key.rawValue
                }
            }
            """

        do {
            try swift.write(to: output, atomically: true, encoding: .utf8)
        } catch {
            fail("[gen_l10n] 写入失败: \(error.localizedDescription)\n")
        }

        print("[gen_l10n] 已生成 L10n.generated.swift （\(keysSorted.count) 个键）")
    }
}
